site_name: Devilranのnote
site_url: https://note.devilran.xyz/
site_author: devilran

theme:
  name: material
  palette:
    #primary: blue grey
  
    - scheme: default # 日间模式
      primary: cyan # 上方的
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  
  features:
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    - navigation.tabs.sticky    #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.top   # 返回顶部的按钮 在上滑时出现
    - search.suggest   # 搜索输入一些字母时推荐补全整个单词
    - search.highlight   # 搜索出的文章关键词加入高亮
    # - navigation.expand   # 打开Tab时左侧目录全部展开
  font:
    text: Fira Code
    code: Fira Code
  language: zh # 一些提示性的文字会变成中文

    
markdown_extensions:
  - pymdownx.arithmatex: # latex 
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

# latex
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

# fira code
extra_css:
  - custom.css
  - https://cdn.jsdelivr.net/gh/tonsky/FiraCode/distr/fira_code.css


extra:
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  social:
    # - icon: fontawesome/brands/twitter  
      # link: https://twitter.com/wcowin_
    - icon: fontawesome/brands/github
      link: https://github.com/devilran6
    # - icon: fontawesome/brands/bilibili
      # link: https://space.bilibili.com/1407028951?spm_id_from=333.1007.0.0
    # - icon: fontawesome/solid/paper-plane
      # link: mailto:<1135801806@qq.com> #联系方式


# [Navigtion]
nav: 
  - Home: Home.md
  - ACM:
    - Knowledge:
      - DP: ACM/Knowledge/DP/换根dp.md
    - CF:
      - div2_892: ACM/CF/div2_892.md
      - div2_893: ACM/CF/div2_893.md
      - div2_899: ACM/CF/div2_899.md
      - edu_155: ACM/CF/edu_155.md
    - 模拟vp:
      - CCPC 2022 绵阳: ACM/模拟vp/ccpc2022mianyang.md
      - ICPC 2023 网络赛第二场: ACM/模拟vp/icpc网络赛第二场.md
      - CCPC 2023 湘潭邀请赛: ACM/模拟vp/ccpc2023xiangtan_yaoqingsai.md
    - 专题训练:
      - Math:
        - CF数学: ACM/专题训练/Math/CF数学.md
        - LG数学: ACM/专题训练/Math/LG数学.md
  - ML:
    - Pytorch的基本用法: ML/Pytorch.md
    - 基本模型:
      - 线性回归: ML/基本模型/linear_model.md
      - CNN: ML/基本模型/cnn.md
      - RNN: ML/基本模型/rnn.md
      - Diffusion: ML/基本模型/diffusion.md
  - Linux:
    - Linux: Linux/Linux.md
  - OS:
    - OS: OS/os.md
  - CTF:
    - CTF: CTF/CTF.md
  - 关于:
    - 个人履历: about/devilran.md
